# Generated by Django 2.0.2 on 2018-02-15 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_publication_publicationcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationcontent',
            name='post',
            field=models.TextField(null=True),
        ),
    ]
